# Project Normandy
# @author RealTwo-Space
#
# travis ci settings
#


language: java
jdk:
  - oraclejdk8
  - oraclejdk7

# excute tests in only master and dev branch
branches:
  only:
    - master
    - dev

after_success:
  - bash <(curl -s https://codecov.io/bash)